[package]
name = "bucket_finder"
version = "0.1.0"
authors = ["Arvindh Kumar Chandran <arv1ndh@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
